#include "vision/detection.hpp"
#include "vision/pipeline.hpp"
#include "vision/tflite_wrapper.hpp"
#include <opencv2/imgproc.hpp>
#include <chrono>
#include <mutex>
#include <vector>

// Embedded symbols generated by xxd
extern "C" {
extern unsigned char detect_tflite[];
extern unsigned int  detect_tflite_len;
extern unsigned char labelmap_txt[];
extern unsigned int  labelmap_txt_len;
}

namespace vision {

    static std::vector<std::string> g_labels;
    static cv::Mat g_lastRgba;
    static std::mutex g_rgbaMutex;

    static double laplacianVar(const cv::Mat& gray) {
        cv::Mat lap; cv::Laplacian(gray, lap, CV_64F);
        cv::Scalar mu, sigma; cv::meanStdDev(lap, mu, sigma);
        return sigma.val[0]*sigma.val[0];
    }
    static double glarePercent(const cv::Mat& gray) {
        int bright = cv::countNonZero(gray > 250);
        return 100.0 * double(bright) / double(gray.total());
    }
    static double meanBrightness(const cv::Mat& gray) { return cv::mean(gray)[0]; }

    static std::vector<std::string> splitLines(const char* data, size_t n) {
        std::vector<std::string> out; out.reserve(128);
        size_t i=0, start=0;
        while (i<n) {
            if (data[i]=='\n' || i==n-1) {
                size_t end = (data[i]=='\n') ? i : i+1;
                std::string s(data+start, data+end);
                if (!s.empty() && s.back()=='\r') s.pop_back();
                if (!s.empty()) out.push_back(s);
                start = i+1;
            }
            ++i;
        }
        return out;
    }

    cv::Mat yuv420ToRgba(const uint8_t* y, const uint8_t* u, const uint8_t* v,
            int width, int height,
            int yRowStride, int uRowStride, int vRowStride,
            int uPixelStride, int vPixelStride) {
        const int ySize = width*height;
        const int cW = width/2, cH = height/2, cSize = cW*cH;
        std::vector<uint8_t> i420; i420.resize(ySize + 2*cSize);

        for (int r=0;r<height;++r) {
            memcpy(i420.data()+r*width, y + r*yRowStride, width);
        }
        uint8_t* uDst = i420.data()+ySize;
        uint8_t* vDst = uDst + cSize;
        for (int r=0;r<cH;++r) {
            const uint8_t* uRow = u + r*uRowStride;
            const uint8_t* vRow = v + r*vRowStride;
            for (int c=0;c<cW;++c) {
                uDst[r*cW+c] = uRow[c*uPixelStride];
                vDst[r*cW+c] = vRow[c*vPixelStride];
            }
        }
        cv::Mat src(height + height/2, width, CV_8UC1, i420.data());
        cv::Mat rgba(height, width, CV_8UC4);
        cv::cvtColor(src, rgba, cv::COLOR_YUV2RGBA_I420);
        return rgba;
    }

    bool pipelineInitializeEmbedded(const std::vector<std::string>& labels, const InitOptions& opt) {
        std::vector<std::string> lbs = labels;
        if (lbs.empty()) {
            lbs = splitLines(reinterpret_cast<const char*>(labelmap_txt), (size_t)labelmap_txt_len);
        }
        g_labels = lbs;
        tfliteSetLabels(g_labels);
        return tfliteInitFromBuffer(detect_tflite, (size_t)detect_tflite_len, opt.tfl);
    }

    Detections pipelineProcessYuv(const YuvFrame& f, const ProcessConfig& cfg) {
        auto t0 = std::chrono::steady_clock::now();
        Detections out;

        cv::Mat rgba = yuv420ToRgba(f.y, f.u, f.v, f.width, f.height,
                f.yRowStride, f.uRowStride, f.vRowStride,
                f.uPixelStride, f.vPixelStride);
        {
            std::lock_guard<std::mutex> lk(g_rgbaMutex);
            g_lastRgba = rgba.clone();
        }
        cv::Mat gray; cv::cvtColor(rgba, gray, cv::COLOR_RGBA2GRAY);
        out.blurVar = laplacianVar(gray);
        out.glarePercent = glarePercent(gray);
        out.brightness = meanBrightness(gray);

        std::vector<Detection> det = tfliteDetect(rgba, cfg.scoreThreshold);
        for (auto& d : det) {
            out.boxes.insert(out.boxes.end(), {d.left, d.top, d.right, d.bottom});
            out.scores.push_back(d.score);
            out.classes.push_back(d.classId);
        }

        auto t1 = std::chrono::steady_clock::now();
        out.processingMs = std::chrono::duration_cast<std::chrono::milliseconds>(t1-t0).count();
        return out;
    }

    bool pipelineEncodeLastRgbaToJpeg(int quality, std::vector<uint8_t>& out) {
        std::lock_guard<std::mutex> lk(g_rgbaMutex);
        if (g_lastRgba.empty()) return false;
        std::vector<int> params = { cv::IMWRITE_JPEG_QUALITY, std::max(0,std::min(100,quality)) };
        return cv::imencode(".jpg", g_lastRgba, out, params);
    }

} // namespace vision
