function(configure_opencv)
    cmake_parse_arguments(CONFIGURE "" "ENABLE_THREADING;ENABLE_SIMD;ENABLE_INTRINSICS;ENABLE_JPEG;ENABLE_PNG;ENABLE_FILE_SYSTEM_SUPPORT;ENABLE_LAPACK" "" ${ARGN})
    include(FetchContent)
    set(FETCHCONTENT_QUIET FALSE)

    FetchContent_Declare(
            opencv
            GIT_REPOSITORY https://github.com/opencv/opencv.git
            GIT_TAG 4.10.0
            GIT_PROGRESS TRUE
            EXCLUDE_FROM_ALL
    )

    set(WITH_V4L OFF)
    set(WITH_FFMPEG OFF)
    set(WITH_TIFF OFF)
    set(WITH_GSTREAMER OFF)
    set(WITH_MSMF OFF)
    set(WITH_DSHOW OFF)
    set(WITH_AVFOUNDATION OFF)
    set(WITH_1394 OFF)
    set(WITH_MATLAB OFF)
    set(WITH_CUDA OFF)
    set(WITH_OPENGL OFF)
    set(WITH_CAROTENE OFF)
    set(WITH_WEBP OFF)
    set(WITH_OPENJPEG OFF)
    set(WITH_JASPER OFF)
    set(WITH_OpenCL OFF)
    set(WITH_OPENCLAMDFFT OFF)
    set(WITH_OPENCLAMDBLAS OFF)
    set(WITH_IPP OFF)
    set(WITH_OPENMP OFF)
    set(WITH_OBSENSOR OFF)
    set(WITH_FLATBUFFERS OFF)
    set(WITH_LAPACK OFF)
    set(BUILD_ITT OFF)
    set(BUILD_IPP_IW OFF)
    set(BUILD_PROTOBUF OFF)
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_TESTS OFF)
    set(BUILD_PERF_TESTS OFF)
    set(BUILD_DOCS OFF)
    set(BUILD_EXAMPLES OFF)
    set(BUILD_opencv_world OFF)
    set(BUILD_opencv_core ON)
    set(BUILD_opencv_imgproc ON)
    set(BUILD_opencv_imgcodecs OFF)

    if (CONFIGURE_ENABLE_JPEG STREQUAL "ON")
        set(WITH_JPEG ON)
        set(BUILD_JPEG ON)
        set(BUILD_opencv_imgcodecs ON)
        set(ENABLE_LIBJPEG_TURBO_SIMD OFF)
    endif ()
    if (CONFIGURE_ENABLE_PNG STREQUAL "ON")
        set(WITH_PNG ON)
        set(BUILD_PNG ON)
        set(BUILD_opencv_imgcodecs ON)
    endif ()
    if (CONFIGURE_ENABLE_FILE_SYSTEM_SUPPORT STREQUAL "ON")
        set(OPENCV_DISABLE_FILESYSTEM_SUPPORT OFF)
    else()
        set(OPENCV_DISABLE_FILESYSTEM_SUPPORT ON)
    endif ()
    if (CONFIGURE_ENABLE_INTRINSICS STREQUAL "ON")
        set(CV_ENABLE_INTRINSICS ON)
    else()
        set(CV_ENABLE_INTRINSICS OFF)
    endif ()
    if (CONFIGURE_ENABLE_THREADING STREQUAL "ON")
        set(WITH_PTHREADS_PF ON)
    endif ()

    FetchContent_MakeAvailable(opencv)

    add_library(opencv INTERFACE)
    set(OPENCV_LIBRARY_TARGETS opencv_core opencv_imgproc)
    set(OPENCV_INCLUDE_DIRS
            ${OPENCV_CONFIG_FILE_INCLUDE_DIR}
            ${OPENCV_MODULE_opencv_core_LOCATION}/include
            ${OPENCV_MODULE_opencv_imgproc_LOCATION}/include
    )
    if (BUILD_opencv_imgcodecs)
        list(APPEND OPENCV_LIBRARY_TARGETS opencv_imgcodecs)
        list(APPEND OPENCV_INCLUDE_DIRS ${OPENCV_MODULE_opencv_imgcodecs_LOCATION}/include)
    endif ()

    target_include_directories(opencv INTERFACE ${OPENCV_INCLUDE_DIRS})
    target_link_libraries(opencv INTERFACE ${OPENCV_LIBRARY_TARGETS})
endfunction()
